# Generated by Django 4.2.24 on 2025-09-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('Type', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
                ('Phone', models.BigIntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('loginid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FakeNewsDetectionApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(blank=True, max_length=1000, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('loginid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FakeNewsDetectionApp.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(blank=True, max_length=1000, null=True)),
                ('Reply', models.CharField(blank=True, max_length=1000, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('loginid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FakeNewsDetectionApp.usertable')),
            ],
        ),
    ]
