# Generated by Django 4.2.24 on 2025-09-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsDetectionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complainttable',
            old_name='loginid',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='feedbacktable',
            old_name='loginid',
            new_name='userid',
        ),
    ]
